version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: fastapi_app
    expose:
      - "3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
