name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      
      - name: Build Images with Docker Compose
        run: docker compose build

      
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --detach --service fastapi-book-project
