name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build Docker images using Docker Compose v2 syntax.
      - name: Build Images with Docker Compose
        run: docker compose build

      # Install the Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Deploy the project using Railway CLI (token is picked up automatically)
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --detach
