name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t fastapi-nginx-app .

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Wait for previous deployment to finish
        run: |
          echo "Checking for active deployment..."
          # Loop until no active deployment is found
          while railway status | grep -qi "active"; do
            echo "Previous deployment still active, waiting 15 seconds..."
            sleep 15
          done

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -o pipefail
          echo "Starting deployment..."
          output=$(railway up --detach --service fastapi-book-project 2>&1)
          exit_code=$?
          echo "$output"
          if [ $exit_code -ne 0 ]; then
            if echo "$output" | grep -qi "Deployment cancelled"; then
              echo "Benign 'Deployment cancelled' detected; ignoring error."
            else
              echo "Unexpected deployment error detected."
              exit $exit_code
            fi
          fi

      - name: Post-deployment delay
        run: |
          echo "Waiting 30 seconds for graceful shutdown of previous instance..."
          sleep 30
